import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from "next-themes";
import "./globals.css";

import { Navbar } from "@/components/Navbar";
import { Footer } from "@/components/Footer";
import { PopupWidget }  from "@/components/PopupWidget";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "SAIF AI-BASE",
  description: "Generated by SAIF 24Gr",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ThemeProvider attribute="class">
    <Navbar />
    <div>{children}</div>
    {/* <Footer /> */}

    <PopupWidget />
  </ThemeProvider>
    // <html lang="en" suppressHydrationWarning>
    //   <body className={inter.className}>
    //     <ThemeProvider attribute="class">
    //       <Navbar />
    //       <div>{children}</div>
    //       {/* <Footer /> */}
     
    //       <PopupWidget />
    //     </ThemeProvider>
    //     <footer></footer>
    //   </body>
    // </html>
  );
}
